#!/bin/bash

# --- Path Configuration ---
# Point these to the exact location of your binaries in /opt
DOCKER="/usr/bin/docker"

# --- Load Shared Functions ---
source "/usr/local/bin/common_functions.sh"

# 1. Stop container
$DOCKER stop $1
# 2. Remove container
$DOCKER rm $1
# 3. Update containers
$DOCKER compose pull
$DOCKER compose up -d
# 4. Cleanup
# Removes unused images and volumes to free up disk space
$DOCKER image prune -af
$DOCKER volume prune -f
log "Updated container $1"
