#!/bin/bash

#update system
apt update
apt full-upgrade -y
apt autoremove -y

#update docker
docker compose pull
docker compose up -d
docker image prune -af
docker volume prune -f


#docker stop $(docker ps --format '{{.Names}}')
#docker rm $(docker ps --format '{{.Names}}')
